from application.views import documents
from application.views import drawing
from application.views import error_handlers
from application.views import home
from application.views import part
from application.views import product
from application.views.htmx import part_htmx
from application.views.htmx import drawing_htmx
from application.views.htmx import product_htmx
from application.views.htmx import document_queries
