# application/pycatia_scripts/tools/image_to_drawing.py
import cv2
import numpy as np
from pathlib import Path
from typing import List, Tuple, Dict
from pycatia.drafting_interfaces.drawing_sheet import DrawingSheet
from pycatia.enumeration.enumeration_types import cat_text_anchor_position

from application.pycatia_scripts.drawing.new_drawing_support.background_view import get_background_view_and_factory
from application.pycatia_scripts.drawing.new_drawing_support.text_properties import set_text_properties


class ImageToDrawingConverter:
    """Convert image analysis results to PyCATIA drawing elements"""

    def __init__(self, scale_factor: float = 0.1):
        """
        Initialize converter
        scale_factor: Convert pixels to millimeters (default: 0.1mm per pixel)
        """
        self.scale_factor = scale_factor
        self.line_thickness_map = {
            'thin': 1,      # 0.18mm
            'normal': 2,    # 0.35mm
            'thick': 3,     # 0.7mm
            'very_thick': 4 # 1.0mm
        }
        self.font_size_map = {
            'small': 2.0,    # 2.0mm
            'normal': 2.5,   # 2.5mm
            'large': 3.5,    # 3.5mm
            'title': 5.0     # 5.0mm
        }

    def pixel_to_catia_coords(self, x: int, y: int, image_height: int) -> Tuple[float, float]:
        """Convert pixel coordinates to CATIA coordinates (origin at bottom-left)"""
        catia_x = x * self.scale_factor
        catia_y = (image_height - y) * self.scale_factor  # Flip Y axis
        return catia_x, catia_y

    def draw_lines(self, sheet: DrawingSheet, lines: List[Dict], image_height: int):
        """
        Draw lines from cv2 analysis results

        Args:
            lines: List of dicts with keys: x1, y1, x2, y2, thickness
            image_height: Height of source image for coordinate conversion
        """
        background_view, factory_2d, main_view = get_background_view_and_factory(sheet)
        selection = sheet.application.active_document.selection

        # Group lines by thickness for efficient rendering
        lines_by_thickness = {}

        for line in lines:
            thickness = line.get('thickness', 'normal')
            if thickness not in lines_by_thickness:
                lines_by_thickness[thickness] = []

            # Convert coordinates
            x1, y1 = self.pixel_to_catia_coords(line['x1'], line['y1'], image_height)
            x2, y2 = self.pixel_to_catia_coords(line['x2'], line['y2'], image_height)

            catia_line = factory_2d.create_line(x1, y1, x2, y2)
            lines_by_thickness[thickness].append(catia_line)

        # Apply thickness to each group
        for thickness, line_group in lines_by_thickness.items():
            if line_group:
                selection.clear()
                for line in line_group:
                    selection.add(line)

                vp = selection.vis_properties
                thickness_value = self.line_thickness_map.get(thickness, 2)
                vp.set_real_width(thickness_value, 0)

    def draw_text(self, sheet: DrawingSheet, text_elements: List[Dict], image_height: int):
        """
        Draw text from OCR results

        Args:
            text_elements: List of dicts with keys: text, x, y, font_size
            image_height: Height of source image for coordinate conversion
        """
        background_view, factory_2d, main_view = get_background_view_and_factory(sheet)
        texts = background_view.texts

        for text_elem in text_elements:
            # Convert coordinates
            x, y = self.pixel_to_catia_coords(
                text_elem['x'], text_elem['y'], image_height
            )

            # Get font size
            font_size = self.font_size_map.get(
                text_elem.get('font_size', 'normal'), 2.5
            )

            # Create text element
            text = texts.add(text_elem['text'], x, y)
            text.anchor_position = cat_text_anchor_position.index('catBottomLeft')

            # Apply text properties
            set_text_properties(text, size=font_size)

    def generate_drawing_script(self, image_path: str, output_script_path: str):
        """
        Generate a complete PyCATIA script from image analysis

        Args:
            image_path: Path to source image
            output_script_path: Path for generated Python script
        """
        # Analyze image (assuming cv2 analysis is working)
        lines, text_elements = self.analyze_image(image_path)

        # Generate script content
        script_content = f'''#!/usr/bin/env python3
"""
Auto-generated PyCATIA script from image: {Path(image_path).name}
Generated by ImageToDrawingConverter
"""

from pathlib import Path
from pycatia.drafting_interfaces.drawing_sheet import DrawingSheet
from application.pycatia_scripts.com_objects import get_app_object
from application.pycatia_scripts.image_analysis.image_to_drawing import ImageToDrawingConverter

def create_drawing_from_image():
    """Create CATIA drawing from analyzed image data"""

    # Get CATIA application
    application = get_app_object()
    if not application:
        print("CATIA application is not running")
        return

    # Create new drawing
    documents = application.documents
    drawing_document = documents.add('Drawing')
    drawing = drawing_document.drawing_root
    sheet = drawing.sheets.active_sheet

    # Set paper size (A3 by default)
    sheet.paper_size = 5  # A3
    sheet.name = "Image-Based Drawing"

    # Initialize converter
    converter = ImageToDrawingConverter(scale_factor=0.1)

    # Image dimensions for coordinate conversion
    image_height = {self.get_image_height(image_path)}

    # Draw lines
    lines_data = {lines}
    converter.draw_lines(sheet, lines_data, image_height)

    # Draw text
    text_data = {text_elements}
    converter.draw_text(sheet, text_data, image_height)

    print("Drawing created successfully from image")

if __name__ == "__main__":
    create_drawing_from_image()
'''

        # Write script to file
        with open(output_script_path, 'w', encoding='utf-8') as f:
            f.write(script_content)

        print(f"Script generated: {output_script_path}")

    def analyze_image(self, image_path: str) -> Tuple[List[Dict], List[Dict]]:
        """
        Analyze image using cv2 (assuming this is working correctly)

        Returns:
            Tuple of (lines, text_elements)
        """
        # Load image
        image = cv2.imread(image_path)
        if image is None:
            raise ValueError(f"Cannot load image: {image_path}")

        height, width = image.shape[:2]

        # Extract lines (assuming cv2 analysis is working)
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        edges = cv2.Canny(gray, 50, 150, apertureSize=3)

        # Use HoughLinesP to detect line segments
        lines = cv2.HoughLinesP(edges, 1, np.pi/180, threshold=100,
                               minLineLength=30, maxLineGap=10)

        line_data = []
        if lines is not None:
            for line in lines:
                x1, y1, x2, y2 = line[0]

                # Determine line thickness based on line properties
                thickness = self.determine_line_thickness(image, x1, y1, x2, y2)

                line_data.append({
                    'x1': x1, 'y1': y1, 'x2': x2, 'y2': y2,
                    'thickness': thickness
                })

        # Extract text (using OCR - placeholder implementation)
        text_elements = self.extract_text_from_image(image)

        return line_data, text_elements

    def determine_line_thickness(self, image: np.ndarray, x1: int, y1: int, x2: int, y2: int) -> str:
        """Determine line thickness based on image analysis"""
        # Sample points along the line to determine thickness
        num_samples = 10
        thickness_values = []

        for i in range(num_samples):
            t = i / (num_samples - 1)
            x = int(x1 + t * (x2 - x1))
            y = int(y1 + t * (y2 - y1))

            # Sample perpendicular to line direction
            thickness_values.append(self.measure_line_thickness_at_point(image, x, y, x1, y1, x2, y2))

        avg_thickness = np.mean(thickness_values)

        # Map to thickness categories
        if avg_thickness < 2:
            return 'thin'
        elif avg_thickness < 4:
            return 'normal'
        elif avg_thickness < 6:
            return 'thick'
        else:
            return 'very_thick'

    def measure_line_thickness_at_point(self, image: np.ndarray, x: int, y: int,
                                      x1: int, y1: int, x2: int, y2: int) -> float:
        """Measure line thickness at a specific point"""
        # Simplified thickness measurement
        # In practice, this would analyze pixel intensity perpendicular to line
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

        # Sample perpendicular direction
        dx = x2 - x1
        dy = y2 - y1
        length = np.sqrt(dx**2 + dy**2)

        if length == 0:
            return 1.0

        # Perpendicular direction
        perp_x = -dy / length
        perp_y = dx / length

        # Measure thickness
        thickness = 0
        for offset in range(-10, 11):
            sample_x = int(x + offset * perp_x)
            sample_y = int(y + offset * perp_y)

            if (0 <= sample_x < image.shape[1] and
                0 <= sample_y < image.shape[0]):
                if gray[sample_y, sample_x] < 128:  # Dark pixel
                    thickness += 1

        return thickness

    def extract_text_from_image(self, image: np.ndarray) -> List[Dict]:
        """Extract text elements from image (OCR placeholder)"""
        # This would use pytesseract or similar OCR library
        # For now, return placeholder text elements

        text_elements = [
            {
                'text': 'SAMPLE TEXT',
                'x': 50,
                'y': 50,
                'font_size': 'normal'
            },
            {
                'text': 'Title',
                'x': 100,
                'y': 100,
                'font_size': 'title'
            }
        ]

        return text_elements

    def get_image_height(self, image_path: str) -> int:
        """Get image height for coordinate conversion"""
        image = cv2.imread(image_path)
        if image is None:
            return 0
        return image.shape[0]


# Usage example
if __name__ == "__main__":
    converter = ImageToDrawingConverter(scale_factor=0.1)

    # Generate script from image
    image_path = "path/to/your/image.png"
    output_script = "generated_drawing.py"

    converter.generate_drawing_script(image_path, output_script)
